---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-deployment
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local